# -----------------------------------------------------------------------------
# File: docker-compose.override.yml
# Purpose: Development overrides for digi-infrastructure
# Related: docker-compose.yml
# Tags: compose, development, override
# -----------------------------------------------------------------------------

services:
  postgres:
    ports:
      - "5432:5432" # Expose for local development
    environment:
      POSTGRES_MULTIPLE_DATABASES: "digi_core,lernmi,beep_boop,test,pcs,cvpunk,stackr,bitscrow,devao"
      POSTGRES_USER: "digi"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-digi}"

  neo4j:
    ports:
      - "7474:7474" # Browser interface
      - "7687:7687" # Bolt protocol

  qdrant:
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API

  redis:
    ports:
      - "6379:6379" # Redis CLI

  grafana:
    ports:
      - "3000:3000" # Web interface

  prometheus:
    ports:
      - "9090:9090" # Metrics interface
