# -----------------------------------------------------------------------------
# File: monitoring/grafana/provisioning/datasources/prometheus.yml
# Purpose: Grafana datasource provisioning configuration
# Related: monitoring/prometheus.yml
# Tags: grafana, monitoring, datasources
# -----------------------------------------------------------------------------

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true


